name: Generate Sitemap

on:
  schedule:
    - cron: '42 17 * * *'
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Generate Sitemap
        run: npm run generate-sitemap

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sitemap.xml
          git commit -m "Generate sitemap"
          git push
