name: Update Sitemap

on:
  schedule:
    - cron: '2 17 * * *' # Run every day at 00:00 (midnight) UTC

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Generate sitemap
      run: |
        npm run generate-sitemap
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update sitemap.xml'
        file_pattern: public/sitemap.xml